// <auto-generated />
using System;
using BootcampWebApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BootcampWebApi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220623123057_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BootcampWebApi.Entities.Bootcamp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Bootcamps");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2022, 6, 23, 12, 30, 57, 621, DateTimeKind.Utc).AddTicks(3766),
                            Name = "Arvato1"
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2022, 6, 23, 12, 30, 57, 621, DateTimeKind.Utc).AddTicks(3769),
                            Name = "Arvato2"
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2022, 6, 23, 12, 30, 57, 621, DateTimeKind.Utc).AddTicks(3770),
                            Name = "Arvato3"
                        });
                });

            modelBuilder.Entity("BootcampWebApi.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("BootcampId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BootcampId = 0,
                            Name = "Ahmet",
                            Status = false
                        },
                        new
                        {
                            Id = 2,
                            BootcampId = 0,
                            Name = "Mehmet",
                            Status = false
                        },
                        new
                        {
                            Id = 3,
                            BootcampId = 0,
                            Name = "Enes",
                            Status = false
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
